#pragma once

#define MAX_COMPONENTS 10
#define MAX_ENTITIES 10

#define BLOCK_WIDTH 100
#define BLOCK_HEIGHT 100

#define TEXTURE_BLOCK_SIDE 100

#define NUMBER_COMMANDS_REMEMBERED 10

#define FPS 25
